### PR TITLE
BLITscript

### PR DESCRIPTION
**Pull request by MaxMahem**
Still a work in progress, but nearing feature complete.

### CODE REVIEW

**Comment by MaxMahem** [comment]
@Yankes still not done, but much closer. I kind of lost track of where I was going and what I was doing but I got there somehow.

This does almost everything I wanted it to... from the inventory point of view at least.

Vague outline of my approach.
* As before, sprite rendering is bound up in a 'local' class. I also created an Overlay class (no inheritance) that handles drawing the overlays. This was primarily because I needed to be able to pass in different boundbox sizes for the different ways the overlay might be constructed.
* All of the default overlays/indicators are coded in C++. The default script is blank. Scripts can control the display of these options by setting an enum on the Overlay class. I have the default settings defined as some constants for now, but it occurs to me that these options could be defined in a rule file someplace as well. I originally had it implemented as a struct to enable this, but I backed down on that for now.
* These new sprite classes handle virtually all the big-obj rendering except for the ufopedia, which is still handled by ItemRule.
* All rendering occurs directly to the target surface, and not a temporary surface.

Outstand issues as I try and remember them:
* So this code has to pull in a lot of well-known references from the mod rule files and elsewhere, which means a lookup against that map table every time a resource is needed, which isn't great. As an alternative I'm thinking maybe make a struct and stash it in `SavedBattleGame` that contains all the well known references that are needed for rendering the default objects.
* The default indicators make heavy use of constructing new `NumberText`s which doesn't look very optimized (it generates a new set of numbers every constructor call?). Probably wouldn't hurt to optimize it, and/or I think an instance just used for drawing could be stashed in `SavedBattleGame` again.
* I still need to add a way to render text via script. The current roadblock is I don't have easy access to `Mod` to get the fonts needed to initialize this. I could add `SavedBattleGame` to the overlay class to provide access to this, but I've wanted to avoid that. Hmm... maybe this suggests I need that struct in `SavedBattleGame` get passed into my class?
* Looks like there is a limit to the number of parameters I can add to a scripting method? When adding a cropping method along with shading and other options you can end up with quite a lot of parameters. 
* * I don't know if this is some assumption on the template method that can be adjusted
* * or if it makes sense to expose some sort of struct (maybe pair? maybe SDL_Rect which I've used a lot) to bundle some of these options up. 
* * Or to just leave well enough alone. I can do almost everything with the current set of methods.
* And now I remember why I put the options together in a struct, I still need a way to inform the scripting side of things the current context of the execution so they can respond to that information if they like. I'll need to go back and do that. Though I suppose the idea on if the defaults should be exposed to `rul` files also effects how I handle this. If they are exposed to rule file, then it'll probably have a string identifier. If it doesn't, I'll probably favor enum.
* * (Also, I had a little trouble following exactly how to expose a field to the scripts, so I just wrote some helper methods, probably better anyways in the case of a flag-enum).

mmm, I'm sure there are other things but they escape me for now. I had originally intended to do the UnitSprite scripting together with this patch, but this is turning into a lot. So I think I'd like to finish up here, get this reviewed and approved, then move on to it.

Hey also I just wanted to take a moment to thank you for giving my ideas your attention and review. I appreciate it!

**Comment by Yankes** [comment]
I bit busy right now and can't fully answer or look on your code for now, probably in day or two I will manage find some time for that.

**Comment by MaxMahem** [comment]
That's cool, and take your time. I don't honestly don't really need a full review at this time (unless you really want to), as I'm still not (quite) finished. Doing a pull request just seemed like the best way to put up a conversation about my current progress. I'm more looking for your opinion on the above issues to direct my further development.

But take your time either way.

**Comment by MaxMahem** [comment]
@Yankes as ideas are sometimes wont to do; one came to me last night while doing something else. We had talked earlier about the difficulty in pre-loading sprites because of the difficulties in extracting them from the scripting. What if, in order to get around this, we extended the RuleItems node with like a `spriteCache` or something similar? Basically, a sequence of sprite-ids that should get stored in the ruleItem as a Vector or something, allowing a fast lookup. 

In fact, if we wanted to get very fancy, we could allow the `bigSprite` (and the other sprite nodes I suppose) to optionally be sequences themselves. If they are, the first item would be the default one, and the other ones would get loaded in the cache. 

Glancing through the code, the only downside I see to this approach is that `BattleItem` does not have easy access to `Mod` in all the places it might get created, which means the "cache" would have to live in `RuleItem.` This seems like the place for it in any case, since if it was in `BattleItem` it would have to get loaded every time one gets created. However, from a structural point of view, I'm not sure if you guys are trying to keep `RuleItem` clear of `Surface` or not.

Anyways, just some thoughts. And as a reminder, I'm not looking for a review of this pull yet (unless you *really want to*), just your feedback on my comments :).

**Comment by Yankes** [comment]
Yes, only problem would be what `id` will each surface have, Later today I will have more time to discuses this and your previous changes.

**Comment by Yankes** [comment]
(I did not look on code yet)

> @Yankes still not done, but much closer. I kind of lost track of where I was going and what I was doing but I got there somehow.
> 
> This does almost everything I wanted it to... from the inventory point of view at least.
> 
> Vague outline of my approach.
> 
>     * As before, sprite rendering is bound up in a 'local' class. I also created an Overlay class (no inheritance) that handles drawing the overlays. This was primarily because I needed to be able to pass in different boundbox sizes for the different ways the overlay might be constructed.
> 

This could be different function in one class too. I think that two separated places where script hooks are called are
required part of this functionality, as some graphics need to be drawn on top of core of item graphic.

>     * All of the default overlays/indicators are coded in C++. The default script is blank. Scripts can control the display of these options by setting an enum on the Overlay class. I have the default settings defined as some constants for now, but it occurs to me that these options could be defined in a rule file someplace as well. I originally had it implemented as a struct to enable this, but I backed down on that for now.
> 
>     * These new sprite classes handle virtually all the big-obj rendering except for the ufopedia, which is still handled by ItemRule.
> 
>     * All rendering occurs directly to the target surface, and not a temporary surface.
> 
> 
> Outstand issues as I try and remember them:
> 
>     * So this code has to pull in a lot of well-known references from the mod rule files and elsewhere, which means a lookup against that map table every time a resource is needed, which isn't great. As an alternative I'm thinking maybe make a struct and stash it in `SavedBattleGame` that contains all the well known references that are needed for rendering the default objects.
> 

Do you follow behavior and usage of `ItemSprite`? it grab some surface sets too but its only done once per frame.
And same could be in your case, your "Sprite" helper class could cache it and be created once per frame.
That would be 20 to 50 reduction of work wasted on searching for know surfaces.

>     * The default indicators make heavy use of constructing new `NumberText`s which doesn't look very optimized (it generates a new set of numbers every constructor call?). Probably wouldn't hurt to optimize it, and/or I think an instance just used for drawing could be stashed in `SavedBattleGame` again.
> 

Same like previously, you can cache it for one per frame in your "sprite" helper.

>     * I still need to add a way to render text via script. The current roadblock is I don't have easy access to `Mod` to get the fonts needed to initialize this. I could add `SavedBattleGame` to the overlay class to provide access to this, but I've wanted to avoid that. Hmm... maybe this suggests I need that struct in `SavedBattleGame` get passed into my class?
> 

Overlay probably should be "interface" to your script, as you need query multiple other information too (like "where is mouse now?").

>     * Looks like there is a limit to the number of parameters I can add to a scripting method? When adding a cropping method along with shading and other options you can end up with quite a lot of parameters.
> 

reduce number of parameters, use "Overlay" as way to transfer most of state to script hook.

>     * * I don't know if this is some assumption on the template method that can be adjusted
> 
>     * * or if it makes sense to expose some sort of struct (maybe pair? maybe SDL_Rect which I've used a lot) to bundle some of these options up.
> 
>     * * Or to just leave well enough alone. I can do almost everything with the current set of methods.
> 
>     * And now I remember why I put the options together in a struct, I still need a way to inform the scripting side of things the current context of the execution so they can respond to that information if they like. I'll need to go back and do that. Though I suppose the idea on if the defaults should be exposed to `rul` files also effects how I handle this. If they are exposed to rule file, then it'll probably have a string identifier. If it doesn't, I'll probably favor enum.
> 
>     * * (Also, I had a little trouble following exactly how to expose a field to the scripts, so I just wrote some helper methods, probably better anyways in the case of a flag-enum).
> 

It should be simple, but it need be `int` as `enum` would need special binding to allow manipulated its values by scripts.
Beside even if you try expose some fields to script, it will end up as function any way (as this way script interact with C++).

> 
> mmm, I'm sure there are other things but they escape me for now. I had originally intended to do the UnitSprite scripting together with this patch, but this is turning into a lot. So I think I'd like to finish up here, get this reviewed and approved, then move on to it.
> 
> Hey also I just wanted to take a moment to thank you for giving my ideas your attention and review. I appreciate it!

I would suggest focus on only one thing, even skip refactors if possible (or push them independently).
Too many changes at once and Meridian will be unhappy :)



> @Yankes as ideas are sometimes wont to do; one came to me last night while doing something else. We had talked earlier about the difficulty in pre-loading sprites because of the difficulties in extracting them from the scripting. What if, in order to get around this, we extended the RuleItems node with like a `spriteCache` or something similar? Basically, a sequence of sprite-ids that should get stored in the ruleItem as a Vector or something, allowing a fast lookup.
> 

How it will exactly work? Beside for some parts we have already spirte global ids, like for bigob as all are shared in one surface set and every `RuleItem` refer to specific one by offset (and it value include current mod offset too). All sprites in surface set are stored in one big vector for fast access.


> In fact, if we wanted to get very fancy, we could allow the `bigSprite` (and the other sprite nodes I suppose) to optionally be sequences themselves. If they are, the first item would be the default one, and the other ones would get loaded in the cache.
> 
> Glancing through the code, the only downside I see to this approach is that `BattleItem` does not have easy access to `Mod` in all the places it might get created, which means the "cache" would have to live in `RuleItem.` This seems like the place for it in any case, since if it was in `BattleItem` it would have to get loaded every time one gets created. However, from a structural point of view, I'm not sure if you guys are trying to keep `RuleItem` clear of `Surface` or not.
> 

`Mod` already work with `Surface` and its sets, `RuleItem` could refer directly to `Surface`  but problem is that we have lazy loading, this mean we would need update all `RuleItems` too, not only `Mod` and its two surface collections (that you marked as `mutable`).

> Anyways, just some thoughts. And as a reminder, I'm not looking for a review of this pull yet (unless you _really want to_), just your feedback on my comments :).

**Comment by MaxMahem** [comment]
> This could be different function in one class too. I think that two separated places where script hooks are called are required part of this functionality, as some graphics need to be drawn on top of core of item graphic.

I've been pondering this, the issue is in my head I saw the sprite bounds as a sort of class invariant, since it is an data element the scripts rely on, and so didn't really want to change its value after class had been constructed. Thus I passed it in during the constructor, not the draw call. (Though in truth it is kind of a silly thing to worry about since I literally chain the draw call right off the ctor currently, the object is not designed to have any persistent lifetime).

I'll keep pondering it though. Having the two classes is kind of non-ideal I think.

FWIW though for big-obs at least, I'm pretty sure I've taken pretty much all logic that would want to draw on the sprite, since I want to be able to enable/disable them (this also cut down on a small amount of duplication). The only overlapping element that remains is the stack-count, which still works fine.

> > ```
> > * So this code has to pull in a lot of well-known references from the mod rule files and elsewhere, which means a lookup against that map table every time a resource is needed, which isn't great. As an alternative I'm thinking maybe make a struct and stash it in `SavedBattleGame` that contains all the well known references that are needed for rendering the default objects.
> > ```
> 
> Do you follow behavior and usage of `ItemSprite`? it grab some surface sets too but its only done once per frame. And same could be in your case, your "Sprite" helper class could cache it and be created once per frame. That would be 20 to 50 reduction of work wasted on searching for know surfaces.

Maybe we're talking past each other, because the `ItemSprite` ctor [here](https://github.com/MeridianOXC/OpenXcom/blob/f7e8f0b13266800e11cfa95ca2139c9a8d12ae48/src/Battlescape/ItemSprite.cpp#L35) follows the pattern I'd like to avoid. It's going to look up the well-known surface every time it is constructed, which would be once per item for every frame.

But since `FLOOROB.PCK` is well known (as are the surface sets I want), this could be improved to stashing a reference to this in `SaveBattleGame`, which is similar to what I was considering. This reduces the lookup to once per game load.

As far as it goes, though, within my code, I follow `ItemSprite`'s pattern more or less. I don't do lookups unnecessarily. So I'm at about the same one lookup/sprite/frame. But since I need a lot more varied references, I have more lookup calls I need to do (there are a handful of calls that are duplicated, but they are on branches that should be mostly exclusive).

The alternative is to use some kind of static, which works fine until the mods are reloaded, which would require the static's state to be reset. Perfectly doable, but I generally think static state should be avoided as much as possible. In particular, it would require `Mod` or some higher level class to have some knowledge of these child classes way down in the weeds in order to reset the static, which probably isn't desirable. 

> 
> > ```
> > * The default indicators make heavy use of constructing new `NumberText`s which doesn't look very optimized (it generates a new set of numbers every constructor call?). Probably wouldn't hurt to optimize it, and/or I think an instance just used for drawing could be stashed in `SavedBattleGame` again.
> > ```
> 
> Same like previously, you can cache it for one per frame in your "sprite" helper.
> 

Hmm... I didn't think that would possible, but let me give it a shot.

> > ```
> > * I still need to add a way to render text via script. The current roadblock is I don't have easy access to `Mod` to get the fonts needed to initialize this. I could add `SavedBattleGame` to the overlay class to provide access to this, but I've wanted to avoid that. Hmm... maybe this suggests I need that struct in `SavedBattleGame` get passed into my class?
> > ```
> 
> Overlay probably should be "interface" to your script, as you need query multiple other information too (like "where is mouse now?").
> 

This is what I've done. All the data the scripts need to execute is stored there (though it isn't much, just the bounding box mostly). And all the script-calls pass through the class to draw and whatnot.

Anyways, I realize now my hesitance in making a reference to `SaveBattleGame` a class member is somewhat foolish, so I'll just do that.

> > ```
> > * Looks like there is a limit to the number of parameters I can add to a scripting method? When adding a cropping method along with shading and other options you can end up with quite a lot of parameters.
> > ```
> 
> reduce number of parameters, use "Overlay" as way to transfer most of state to script hook.
> 

I'm not sure if this is possible. To do a cropped blit we need to know the following information: `(x, y)positionToBlitTo, (x1, y1, x2, y2)dimensionsOfCrop` then optionally, we might want to know a shade to apply to the blit, and/or a recolor to do. That's 8 variables that might want to be passed. We don't always need all of these, of course. But exposing all 8 seems to hit a limit. 

> 
> It should be simple, but it need be `int` as `enum` would need special binding to allow manipulated its values by scripts. Beside even if you try expose some fields to script, it will end up as function any way (as this way script interact with C++).
> 

Well, my thinking was I could expose a pointer to a `SDL_Rect` as a "crop_rect" and bind some methods to it. Probably something like "createCroppingRect" that returns a pointer to an appropriately formed rect.

> > mmm, I'm sure there are other things but they escape me for now. I had originally intended to do the UnitSprite scripting together with this patch, but this is turning into a lot. So I think I'd like to finish up here, get this reviewed and approved, then move on to it.
> > Hey also I just wanted to take a moment to thank you for giving my ideas your attention and review. I appreciate it!
> 
> I would suggest focus on only one thing, even skip refactors if possible (or push them independently). Too many changes at once and Meridian will be unhappy :)
> 

Yeah well, while I get that, it kind of puts me in a bind. I don't want a massive patch with its tentacles everywhere. But, OTOH, I don't really want to submit a ton of patches with small incremental features as it feels quite a battle to get even a small thing accepted, so... 🤷. Navigating that trade-off is half the reason I'm harassing you :P. Though, being honest their attitude is kind of demotivating. 

> > @Yankes as ideas are sometimes wont to do; one came to me last night while doing something else. We had talked earlier about the difficulty in pre-loading sprites because of the difficulties in extracting them from the scripting. What if, in order to get around this, we extended the RuleItems node with like a `spriteCache` or something similar? Basically, a sequence of sprite-ids that should get stored in the ruleItem as a Vector or something, allowing a fast lookup.
> 
> How it will exactly work? Beside for some parts we have already spirte global ids, like for bigob as all are shared in one surface set and every `RuleItem` refer to specific one by offset (and it value include current mod offset too). All sprites in surface set are stored in one big vector for fast access.
> 

Well when the list is loaded in by mod, it can process the number to the appropriate offset, as it does now. Nothing would change from the user end, the difference would be that internally it would be stored as a vector of these ids, instead of as a single int (though most of the time it would just have the single item.

But now that I think more about it, your right. With it being a vector, there isn't much point to this. Maybe for the lookup of "named" sprites, but I expect those to be the minority. So let's just forget about it.

---

Anyways, I feel like I've fiddled with this enough for now. I'll put the final touches on it tomorrow and get everything wrapped up for review. I appreciate your thoughts as always.

**Comment by Yankes** [comment]
> Maybe we're talking past each other, because the ItemSprite ctor [here](https://github.com/MeridianOXC/OpenXcom/blob/f7e8f0b13266800e11cfa95ca2139c9a8d12ae48/src/Battlescape/ItemSprite.cpp#L35) follows the pattern I'd like to avoid. It's going to look up the well-known surface every time it is constructed, which would be once per item for every frame.

This is true, this was more "I can accept cost once per frame", but of corse better is "Once per game/mission" but require more changes to code. And most of changes like this should go in different PR, or at least in different commit and do not mix with other logic/refactors you adding.

>I'm not sure if this is possible. To do a cropped blit we need to know the following information: (x, y)positionToBlitTo, (x1, y1, x2, y2)dimensionsOfCrop then optionally, we might want to know a shade to apply to the blit, and/or a recolor to do. That's 8 variables that might want to be passed. We don't always need all of these, of course. But exposing all 8 seems to hit a limit.

I mean that you class should store this info, and expose it to script (it could be different class but this more implantation detail).
And in script you call:
```
drawContext.GetPositionToBlitTo.GetX x;
drawContext.GetPositionToBlitTo.GetY y;
```
This will have benefits as at some point I could update script engine to support small structs, and then code would look like:

```
drawContext.GetPositionToBlitTo xy;
```

If you put all in arguments to scripts, I would not be allowed to change API to more ergonomic in future.

> Yeah well, while I get that, it kind of puts me in a bind. I don't want a massive patch with its tentacles everywhere. But, OTOH, I don't really want to submit a ton of patches with small incremental features as it feels quite a battle to get even a small thing accepted, so... 🤷. Navigating that trade-off is half the reason I'm harassing you :P. Though, being honest their attitude is kind of demotivating.

If you post small PR that I was backing, then it will have easy time to be included, as some changes I request from you I could make myself when I visit that part of code.

**Comment by MaxMahem** [comment]
Hey, one last question for you. Is there a preference for naming conventions for public members of non-trivial classes? They are unprefixed in the structs, but they are all trivial. I don't see any point in making some of these members private when they are either const, or I would just have to expose them via a get/set methods anyways.

**Comment by Yankes** [comment]
Probably keep them private and use `getX` and `setX` as assessors. Most class are handed this way.
At least you need some other setters in this class, to make API consistent on one class then best if all members have them.

**Pull request closed without merging**
